version: "3.8"
services:
  api:
    build: ./api
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
      - SESSION_CODE_LENGTH=6
      - HINT_PENALTY=1
      - ALLOW_PARTIAL=true
      - SYNC_INTERVAL_MS=5000
    volumes:
      - ./api:/app
  web:
    build: ./web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000
    volumes:
      - ./web:/app
    depends_on:
      - api
